language: minimal
dist: focal

matrix:
  include:
    - os: linux
      env: NVIM_VERSION=stable
      addons:
        apt:
          - lua-busted
          - neovim
          - scdoc
    - os: linux
      env: NVIM_VERSION=unstable
      addons:
        apt:
          source:
            sourceline: 'ppa:neovim-ppa/unstable'
          packages:
            - lua-busted
            - neovim
            - scdoc
    - os: osx
      osx_image: xcode10.3
      addons:
        homebrew:
          update: true
          packages:
            - neovim
            - scdoc
            - luarocks
  allow_failures:
    - os: linux
      env: NVIM_VERSION=unstable


before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    luarocks --local install busted
  fi

install: make install PREFIX=$HOME/.local

script: |
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
  else
    BUSTED=busted
  fi
  make test BUSTED="$BUSTED"
