language: minimal
dist: focal

matrix:
  include:
    - os: linux
      env: NVIM_VERSION=stable
    - os: linux
      env: NVIM_VERSION=unstable
    - os: osx
      osx_image: xcode10.3
  allow_failures:
    - os: linux
      env: NVIM_VERSION=unstable

addons:
  apt:
    - lua-busted
    - neovim
    - scdoc

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    brew update
    brew install neovim scdoc luarocks
    luarocks --local install busted
  elif [[ "$TRAVIS_OS_NAME" = linux && "$NVIM_VERSION" = unstable ]]; then
    sudo add-apt-repository -y ppa:neovim-ppa/$NVIM_VERSION
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends neovim
  fi

install: make install PREFIX=$HOME/.local

script: |
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
  else
    BUSTED=busted
  fi
  make test BUSTED="$BUSTED"
