language: minimal
dist: focal

matrix:
  include:
    - os: linux
      addons:
        apt: &apt_packages
          - lua-busted
          - neovim
          - scdoc
      env: BUSTED=busted
    - os: linux
      addons:
        apt:
          source: {sourceline: 'ppa:neovim-ppa/unstable'}
          packages: *apt_packages
      env: BUSTED=busted UNSTABLE=true
    - os: osx
      osx_image: xcode10.3
      addons:
        homebrew:
          update: true
          packages:
            - neovim
            - scdoc
            - luarocks
      env: BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
  allow_failures:
    - os: linux
      env: BUSTED=busted UNSTABLE=true

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    luarocks --local install busted
  fi

install: make install PREFIX=$HOME/.local

script: make test BUSTED="$BUSTED"
