language: minimal
dist: focal

addons:
  apt: &apt_packages
    - lua-busted
    - neovim
    - scdoc
  homebrew:
    - neovim
    - scdoc
    - luarocks

matrix:
  include:
    - os: linux
    - os: linux
      env: UNSTABLE=true
      addons:
        apt:
          source: { sourceline: 'ppa:neovim-ppa/unstable' }
          packages: *apt_packages
    - os: freebsd
      addons:
        pkg:
          - neovim
          - scdoc
          - lua51-luarocks
      env: BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
    - os: osx
      # Older versions have trouble with homebrew.  When the osx builds start
      # to fail again or take to long try updating this first.
      osx_image: xcode12.5
      env: BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
  allow_failures:
    - os: linux
      env: UNSTABLE=true

before_install: |
  if [[ "$TRAVIS_OS_NAME" = freebsd ]]; then
    luarocks51 --local install busted
  elif [[ "$TRAVIS_OS_NAME" = osx ]]; then
    luarocks --local install busted
  fi

install: |
  if [[ "$TRAVIS_OS_NAME" = freebsd ]]; then
    gmake install PREFIX=$HOME/.local
  else
    make install PREFIX=$HOME/.local
  fi

script: |
  if [[ "$TRAVIS_OS_NAME" = freebsd ]]; then
    gmake test BUSTED="$BUSTED"
  else
    make test BUSTED="${BUSTED:-busted}"
  fi
