language: shell
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - sourceline: 'ppa:neovim-ppa/unstable'
    packages:
      - pandoc
      - neovim
before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = linux ]]; then
    # Install bats, there is no package for it in old ubuntu versions.
    git clone https://github.com/sstephenson/bats.git
    (cd bats && ./install.sh ~/.local)
  else
    brew update
    brew install neovim pandoc bats
  fi
install: make install PREFIX=$HOME/.local
script: make test
