name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo add-apt-repository -y ppa:neovim-ppa/stable
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends neovim scdoc lua-busted
    - name: Run the test suite
      run: script -ec "make test"
      env:
        TERM: dumb
